### ISSUE TITLE
Wrong hemisphere placement of some locations

### ISSUE THREAD

**Issue by mtb-za** [mishajw/WikiMap#11]
This is a very cool visualisation, so thanks.

Since I am South African, I wanted to see what timeglo.be showed for that. For some reason, there are a bunch of locations in Egypt, rather than South Africa.

https://timeglo.be/1652/2016/South_Africa shows this. What it seems to be doing in some cases is not plotting it in the southern hemisphere. I am fairly sure that this is something wrong with the metadata somewhere, rather than you, but following the links, the locations seem to be correct on Wikipedia.

**Comment by mishajw** [comment]
Thanks for the complement & feedback!

I've looked into it, and it seems that this is due to DBpedia sometimes not registering coordinates as being SE, so we treat them as NE. So the coordinates of South Africa are roughly 25S, 25E, while the coordinates for Egypt are roughly 25N, 25E.

So while there won't be a generic fix to this, I'm working on a manual correction system, and once that is done this'll be at the top of our list to correct!
